### PR TITLE
Feature/fed process

### PR DESCRIPTION
**Pull request by SteveBarnett**
@CSergienko Can you have a look at this and comment, please?
Too much?

### CODE REVIEW

**Comment by CSergienko** [comment]
+1 - I don't think it's too much.

**Comment by hedleyroos** [comment]
You're missing the bit where we are pragmatic and would gladly do two sets of templates if our grand desktop visions can't even fit into a Samsung E250's memory.

**Comment by hedleyroos** [comment]
Also missing Jmbo skeleton for Jmbo sites. Why is Graphite a FED tool?

**Comment by SteveBarnett** [comment]
@hedleyroos re pragmatic: (0_o);
re Jmbo: I wot not of this. Want to add an issue for that?
re Graphite: it is not. It's there from... before.

**Comment by SteveBarnett** [comment]
@hedleyroos Cool. TODO: add Jmbo, multiple template bits.

**Comment by SteveBarnett** [comment]
Closes #50.

**Pull request merged**
